name: Python application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check current dir location
      run: pwd
    
    - name: check Python Version
      run: python --version

    - name: check Node Verion
      run: node --version

    - name: running python script sample.py
      run: python sample.py


    # - name: Set up Python 3.10
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: "3.10"
    # - name: Install Python dependencies
    #   run: |
    #     python -m pip install --upgrade pip
